# https://github.com/bbatsov/ruby-style-guide

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

BlockLength:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/MultilineHashBraceLayout:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

# Comments don't need to be in English only
Style/AsciiComments:
  Enabled: false

# Do not enforce documentation rules
Style/Documentation:
  Enabled: false

# Default 80
Metrics/LineLength:
  Max: 120

# Default 15
Metrics/AbcSize:
  Max: 30
  Exclude:
  - 'db/**/*'

# Default 10
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'db/**/*'

# Default 100
Metrics/ClassLength:
  Max: 200

# TODO: Enable this cop after new release (in current 0.43.0 doesn't work as it is expected)
Style/VariableNumber:
  Enabled: true
